"""Generate the agent-skill API reference from widget trait introspection.

Emits ``src/manywidgets/skill/references/widgets-api.md`` — a single, grouped
catalog with a per-widget trait table and a derived constructor signature. This
reuses the same introspection the docs builder uses (``public_traits`` /
``api_table`` / ``class_for`` from ``build_widget_docs``), so the reference can
never drift from the code.

Unlike the per-widget doc notebooks (gitignored build artifacts), this file is
**committed** — it's small static markdown, and committing guarantees it ships
inside the wheel (so ``manywidgets install-skill`` works offline and the
reference always matches the installed version's API).

Run: python scripts/build_skill_reference.py   (with manywidgets importable)
CI regenerates this and fails on a dirty diff, so keep it committed and current.
"""

from __future__ import annotations

import pathlib

import traitlets

# Sibling module in scripts/; sys.path[0] is this script's dir when run directly.
from build_widget_docs import api_table, class_for, public_traits

ROOT = pathlib.Path(__file__).resolve().parent.parent
WIDGETS_SRC = ROOT / "src" / "manywidgets"
OUT = ROOT / "src" / "manywidgets" / "skill" / "references" / "widgets-api.md"

# Display grouping for the catalog. Widget dir names -> section. Any widget dir
# discovered but not listed here lands in "Other" so new widgets never vanish.
GROUPS: list[tuple[str, list[str]]] = [
    ("Charts & displays", ["chart", "stat", "number_display", "text", "legend"]),
    ("Input controls", ["slider", "range_slider", "dropdown", "toggle", "button", "number_input"]),
    ("Layout containers", ["row", "column", "grid"]),
    ("Linking", ["binder"]),
    ("Lonboard interop", ["layer_toggle", "layer_filter", "filter_binder"]),
]

# Containers take their children positionally as well as via children=[...].
CONTAINERS = {"row", "column", "grid"}


def signature(name: str, cls) -> str:
    """A keyword-arg constructor signature derived from the public traits.

    No-default traits come first so the rendered call is valid Python ordering
    (required-looking args before defaulted kwargs).
    """
    required, defaulted = [], []
    for tname, tr in public_traits(cls):
        if tname == "widget_id":
            continue
        dv = tr.default_value
        if dv is traitlets.Undefined:
            required.append(tname)
        else:
            defaulted.append(f"{tname}={dv!r}")
    cls_name = "".join(p.capitalize() for p in name.split("_"))
    return f"{cls_name}({', '.join(required + defaulted)})"


def discover() -> dict[str, object]:
    """dir name -> widget class, for every widget dir that imports."""
    found = {}
    for doc_path in sorted(WIDGETS_SRC.rglob("doc.md")):
        name = doc_path.parent.name
        cls = class_for(name)
        if cls is None:
            print(f"skip {name} (class not importable — is the [lonboard] extra installed?)")
            continue
        found[name] = cls
    return found


def main() -> int:
    found = discover()
    grouped = {g: [] for g, _ in GROUPS}
    grouped["Other"] = []
    placed = set()
    for group, names in GROUPS:
        for name in names:
            if name in found:
                grouped[group].append(name)
                placed.add(name)
    for name in found:
        if name not in placed:
            grouped["Other"].append(name)

    lines = [
        "# manywidgets — widget API reference",
        "",
        "<!-- GENERATED by scripts/build_skill_reference.py from widget traits. Do not edit by hand. -->",
        "",
        "Every widget is constructed with its traits as keyword arguments "
        "(e.g. `Slider(min=0, max=10, value=5)`). Layout containers (`Row`, "
        "`Column`, `Grid`) also accept children positionally: `Row(a, b)`.",
        "Display a widget by leaving it as the last expression in a notebook cell.",
        "",
        "## Catalog",
        "",
    ]
    for group, _ in GROUPS:
        if grouped[group]:
            cls_names = ", ".join(
                "`" + "".join(p.capitalize() for p in n.split("_")) + "`"
                for n in grouped[group]
            )
            lines.append(f"- **{group}:** {cls_names}")
    if grouped["Other"]:
        cls_names = ", ".join(
            "`" + "".join(p.capitalize() for p in n.split("_")) + "`"
            for n in grouped["Other"]
        )
        lines.append(f"- **Other:** {cls_names}")
    lines.append("")

    for group, _ in GROUPS:
        names = grouped[group]
        if not names:
            continue
        lines.append(f"## {group}")
        lines.append("")
        for name in names:
            cls = found[name]
            cls_name = "".join(p.capitalize() for p in name.split("_"))
            lines.append(f"### `{cls_name}`")
            lines.append("")
            doc = (cls.__doc__ or "").strip().split("\n\n")[0].strip()
            if doc:
                lines.append(doc)
                lines.append("")
            lines.append("```python")
            lines.append(signature(name, cls))
            lines.append("```")
            lines.append("")
            if name in CONTAINERS:
                lines.append("Also: `%s(child1, child2, ...)` — children passed positionally." % cls_name)
                lines.append("")
            lines.append(api_table(cls))
            lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines).rstrip() + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(found)} widgets)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
